### ISSUE TITLE
SubsamplingScaleImageView doesn't work with picasso.

### ISSUE THREAD

**Issue by cuttingedge03** [davemorrissey/subsampling-scale-image-view#100]
As this custom View does not extend ImageView it doesn't work with picasso. Is there anyway to convert this into ImageView and make it work with picasso?

**Comment by davemorrissey** [comment]
This question has come up a few times - see the closed issues. SSIV needs to work from a file to enable loading of tiles, and picasso is designed to load a complete full resolution Bitmap into an ImageView, so they don't work together. Either find a way to use picasso to download and cache files so that SSIV can display them, or use another image view that supports gestures but not large images.
