### ISSUE TITLE
Device specific lag in ViewPager

### ISSUE THREAD

**Issue by zmnpl** [davemorrissey/subsampling-scale-image-view#218]
Hi, 

I'm experiencing very weird lag on my Moto X Pure.
I've SubsamplingScaleImageView (match parent,x,y) in a ViewPager without any fancy stuff, very much sticking to the sample, and somehow a lot of bigger Pictures (devices has 21mpx camera) are causing huge Lag (~50 frame jumps) on my Motorola X Pure.

The lag is, when swiping away from the already loaded picture.
First I thought, it was because of the size of the image. But other Images from the same camera/app are working well, even with bigger file sizes. I debugged a lot and tried a lot of stuff (i.e. setParallelLoadingEnabled, OffscreenPageLimit, ...) until I almost gave up and tried other devices. On the Oneplus One, and even on the MotoG 2014 the exact same pictures with the exact same AppBuild are not lagging and buttery smooth, which is pretty weird, as both devices have much weaker hardware. Therefore I assume there might be something in the operating system of my X, though I certainly have no clue where to point my finger at. The Oneplus runs Android 5, while the Moto G is on Android 6, like my X. So major Android version doesn't seem to be the factor as well. I attached two images from my Moto X camera. One with about 9 MB not causing lag, and the other with about 7 MB causing lag for the option to maybe reproduce the issue.

As it seems device/system related I thought it worth posting. It could hint towards iusses with specific library versions or similar...(?) Is there any method, which could lead to clues on the issues or is this maybe somthing known/expected?

Best regards
Simon

Edit: Sorry, filenames get changed with upload. The one with the car mirror is the bigger pic, that doesn't cause lag.

![lag](https://cloud.githubusercontent.com/assets/9001667/15859975/87a11072-2cc7-11e6-8e74-d98f1ff26b49.jpg)
![no_lag](https://cloud.githubusercontent.com/assets/9001667/15859976/87ca71b0-2cc7-11e6-81e8-86ce2b637782.jpg)

**Comment by kakai248** [comment]
I'm also having lag in a viewpager and don't know the real reason. I'm using a very basic example, saving the images to the disk using Glide and then setting the ImageURI using the File that Glide gives me. So I'm actually using a file instead of bitmaps.

It only happens when I'm scrolling to the next page, scrolling to the previous page is very fluid. I'm also suffering from the visibility problem described in #127.

I'm testing with the images in this album: https://imgur.com/a/msKtB

They are big but not big enough to pass my device texture size (Nexus 5, 4096x4096). When I swipe to the next fragment of the viewpager, I see a lag spike in CPU usage, in the kernel. The image is not drawn at first, but even after being drawn the CPU spike continues. This happens with tiling on or off, doesn't matter.

Loading as a bitmap (instead of uri) solves the problem. However I lose the tiling.

**Comment by zmnpl** [comment]
Well it is the opposite for me. Scrolling away from the picture is causing lag, while scrolling on it, loading, zooming and so on are fine without any issues.

**Comment by franciscofranco** [comment]
I have the same exact issue ya'll reporting. The only way I can make it stop is using a lower minimumTileDpi to like 104. The "un-zoomed" picture quality is degraded, but at least it doesn't lag anymore when swiping through the viewPager. I would love a public access to the reset() method so I could cancel every decoding work as soon the user swipes to another page.

**Comment by zmnpl** [comment]
Francis, is that specific for certain devices / images for you as well? If so, which devices and do you maybe have images that cause the issue?

**Comment by franciscofranco** [comment]
Device is irrelevant. My test devices are the following: Nexus 6P, 6, 5X, 5, 4, 9, 10, One Plus One, One Plus 2 and One Plus X. Image type is irrelevant as well. Code is straightforward, pretty similar to the sample. My use case is simple, I use Glide for 80x80 thumbnails, I click a thumb, I call Glide to re-use the 80x80 cached bitmap and once that is up I pass the URI of the actual picture to this library and replace the Glide'd image. Sounds a bit overwhelming but it's way faster to re-use an already decoded, resampled & resized cached bitmap as a "preview" instead of relying on this lib to present a preview and then decode the picture. This is for my use case though, I spent a couple weeks debugging and testing all possible combinations. If I don't use a custom minimumTileDpi I encounter lag if I swipe on my ViewPager while the picture is being decoded by this lib, and if I swipe fast there are a couple hangs in what looks like the lib is still decoding the previous picture so it has to wait for something until it starts to decode the new picture in the foreground. And yes I use the parallel threading option.

My ViewPager is pretty lightweight too, I don't use fragments or anything, I simply replace the views inside so I save some overhead of re-creating new fragments for every swipe.

Nevertheless I love this lib, and I don't plan on not using it. I did a couple tests yesterday after reading this and I settled for 196 as minimumTileDpi. It's not as "fluid" as using lower dpi value (which is fairly obvious) the picture quality gain against my old value (104) is enough to justify and with tiling the users can just zoom for more detail.

I hope that was helpful.

**Comment by zmnpl** [comment]
Your input is appreciated. Though I don't believe we have the same problem. As clearly stated in the OP I'm experiencing issues **only on one specific device** with **some images**. Same Images, same code, even weaker device -> No issue.
To make sure I tried minimum DPI as well, which has no effect for me.

**Comment by franciscofranco** [comment]
> I Still wonder, why I'm facing it only on the one device/image combination.

I can almost guess it's because lower end devices have:

1. lower resolution so the inSample calculation is more aggressive on the decode
2. smaller max texture size which also limits the inSample calculation

On powerful devices we can _assume_ there's enough juice, resolution & texture size to be a little more forgiven in the scaling math. This is really hard to get right, even Google on Photos hasn't nailed it and I can trigger lag fairly easily if I try enough. Although I think this lib already does a fucking amazing job at having a working middle ground.

**Comment by kakai248** [comment]
After messing around I managed to improve my situation. Here's what I did to fix/diminish the lag:

I used [this](https://github.com/inorichi/subsampling-scale-image-view) fork because it adds a setMaxBitmapDimensions method. In this method I used 1024 dpi as the maximum tile size.

Then I had to add previews. Before, I was using Glide to load/cache images. However in Glide you can't get the cached image file and a bitmap at the same time. This was fundamental. I had to change to UIL.

Now I tell UIL to load the image and to also generate a bitmap with the dimensions I provide. I get the cached file, use it as the base image and use the scaled bitmap as the preview image.

It's much more fluid now. Here's the code:

```
scaleImageView.setMaxBitmapDimensions(1024);

ImageSize imageSize = new ImageSize(scaleImageView.getWidth(), scaleImageView.getHeight());
imageLoader.loadImage(url, imageSize, null, new SimpleImageLoadingListener() {
    @Override
    public void onLoadingComplete(String imageUri, View view, Bitmap loadedImage) {
        File file = imageLoader.getDiskCache().get(url);

        BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeFile(file.getAbsolutePath(), options);
        int height = options.outHeight;
        int width = options.outWidth;

        scaleImageView.setImage(ImageSource.uri(file.getAbsolutePath()).dimensions(width, height), ImageSource.bitmap(loadedImage));
    }
}, progressListener);
```

**Comment by franciscofranco** [comment]
@kakai248 isn't that a bit overkill? You're basically doing this lib's job of decoding with another lib... The setMaxBitmapDimensions method seems useful, I'll play with it.

**Comment by kakai248** [comment]
To use previews you have to pass a scaled image. If you pass the original image, it will lag. The only way I found was to download the original and also generate a scaled down bitmap.

Using preview makes the image show instantly, which makes the experience fast to the user. Not using it I could notice a small delay while the lib was loading the full image.

**Comment by franciscofranco** [comment]
That makes sense!

**Comment by davemorrissey** [comment]
Sorry I'm late to this party. Device specific issues are hard to reproduce but I think I can see why the Moto X Pure would have a problem - it has an insane screen density of 520ppi.

This library defaults to loading enough image data to at least match the resolution of the screen so with a screen that dense, and assuming a max bitmap size over 4096px, it will load almost any image you throw at it as one tile with a sample size of 1, which needs about 60Mb for your example images. Other devices with a smaller max bitmap size, a smaller screen, or a less dense screen will load the image in tiles and/or subsampled and perform better.

Setting minimumTileDpi to something more sane like 160 or 240 will reduce the quality but not noticeably for most people, and will usually reduce the amount of image data loaded to something the device can better cope with.

Re. a public `reset()`, use `recycle()` but this should only be called after the view is off screen. If you call it when the view pager transition starts the image will disappear.

**Comment by zmnpl** [comment]
Thanks @davemorrissey for that helpful information! That makes the issue perfectly clear and the solution very accepted.

**Comment by qinchong1988** [comment]
my test devices log.

`initialiseBaseLayer maxTileDimensions=16384x16384
getWidth()=720,sWidth()=1080,getHeight()=1280,sHeight()=10800
width scale=0.666667,height scale=0.118519
initialiseTileMap maxTileDimensions=16384x16384
TileLoadTask.doInBackground, tile.sRect=Rect(0, 0 - 1080, 10800), tile.sampleSize=2`

maxTileDimensions is too large.. , i fix it use:
`setMaxTileSize(4069, 4069);`
