### ISSUE TITLE
Load Image from URL is not working

### ISSUE THREAD

**Issue by ShreyashPromact** [davemorrissey/subsampling-scale-image-view#228]
Hello,

This library is really nice. But I want to load image from URL and then apply this effect. Is there any support for that available?

Sincerely,
Shreyash

**Comment by davemorrissey** [comment]
This library is not designed to load images from URLs because it prevents the tiling of large images. Download the image first then pass the downloaded file path to the view.

If you are using an image loader library, see the wiki, past issues and stack overflow to find out how other users have integrated loaders with this view.

**Comment by ShreyashPromact** [comment]
@davemorrissey 

I know how to use loader with loading image. But my concern is only with loading high resolution image from url and also apply such effect on that.

Thanks anyway,

Sincerely,
Shreyash
