### ISSUE TITLE
Long picture won't show while setting maximum dpi.

### ISSUE THREAD

**Issue by jalonray** [davemorrissey/subsampling-scale-image-view#301]
If the maximum dpi use default value, it works fine.
I wish the long picture would fit width and I use code as follow:

`BitmapFactory.Options options = new BitmapFactory.Options();
        options.inJustDecodeBounds = true;
        BitmapFactory.decodeResource(getResources(), resId, options);
        int width = options.outWidth;
        float screenWidth = getResources().getDisplayMetrics().widthPixels;
        float screenDpi = getResources().getDisplayMetrics().xdpi;
        float widthInch = screenWidth / screenDpi;
        int maxDpi = (int) (width / widthInch);
        int minDpi = (int) (maxDpi / 5.0f);
        imageView.setImage(ImageSource.resource(resId));
        imageView.setMaximumDpi(maxDpi);
        imageView.setMinimumDpi(minDpi);
        imageView.setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CUSTOM);
        imageView.setDoubleTapZoomScale(imageView.getMaxScale());
        imageView.setScaleAndCenter(imageView.getMinScale(), new PointF(width / 2f, 0f));`

But it logs:
OpenGLRenderer: Bitmap too large to be uploaded into a texture (1304x17500, max=16384x16384).

If I delete "imageView.setMaximumDpi(maxDpi);" and "imageView.setScaleAndCenter(imageView.getMinScale(), newPosintF(width/2f, 0f);" it works fine.

**Comment by davemorrissey** [comment]
I can't reproduce this. It may be dependent on the image size, view size and screen size/density. I recommend putting the image in assets rather than drawables so you can be sure Android won't scale the image when decoding it. At least make sure the image is in `drawable-nodpi` only.

If you're able to reproduce this, and provide more details of the image, the affected devices, and how your app is set up please let me know.
