### ISSUE TITLE
setPanEnabled

### ISSUE THREAD

**Issue by oskarOlausson** [davemorrissey/subsampling-scale-image-view#317]
When you setPanEnabled to false the function also centers the view (if you are zoomed in). There does not seem to be a way around this. This is really anoying.

**Comment by davemorrissey** [comment]
As a workaround, you can call `getScale()` and `getCenter()` before disabling pan, and then `setScaleAndCenter()` afterwards. I doubt the image will visibly move because rendering is asynchronous.

I know that's not ideal, but this is one of the cases where there isn't a single behaviour that meets everyone's needs, and it's not worth changing the interface or adding a configuration option.

**Comment by oskarOlausson** [comment]
Yes, tjat sas what I eventuellt did
