### ISSUE TITLE
OutOfMemory Exception on Samsung Devices

### ISSUE THREAD

**Issue by avp2306** [davemorrissey/subsampling-scale-image-view#38]
Hello, first of thank you for creating a great library and maintaining it. Totally awesome! You've managed to solve a problem many of us android devs face.

I'm facing an issue where some of the users get an OutOfMemory Exception. I'm using the following code to set the map:

int iDeviceDpi = getResources().getDisplayMetrics().densityDpi;
        float fZoomScale;
        if (iDeviceDpi <= 240) {
            fZoomScale = 0.85f;
        } else {
            fZoomScale = 1.4f;
        }

_imgMap.setImageResource(R.drawable.map);
_imgMap.setDoubleTapZoomScale(fZoomScale);

I'm also using a PNG of about 2MB, and the file size is 5000x4000. It is a map and should not have transparencies, I've also made sure to Uncheck 'Transperency' option in Photoshop just to make sure.

I'm looking for most reliable way to have this working on as many devices as possible, so open to further workaround or tweaks you may advise of. I can also save the file as JPG if that helps.

Thanks in advance!

**Comment by davemorrissey** [comment]
The sample app has a larger PNG than this and I've never had a crash reported, so it should be possible to display this image without any problems. Please could you attach the image so I can check the format?

Is there anything that the affected devices have in common? Maybe a particular version of Android, or all have high density or low density screens? Tablets or phones?

If it's mostly high density screens, you could reduce the amount of image data loaded using `setMinimumTileDpi(180)`. I'm not sure how effective this is, because these devices should have enough memory for big images.

Where you're setting the double tap zoom scale you could also use the density independent method `setDoubleTapZoomDpi(100)` so it will be consistent across all devices, though it's unlikely this causes errors.

Perhaps most importantly, I notice you're using `setImageResource`, which was only added to `SubscamplingScaleImageView` a couple of weeks ago. Make sure you aren't using `ScaleImageView`, which is only for smaller images. You could also try moving the image to assets, that may be more reliable.

**Comment by avp2306** [comment]
Thank you so much for a prompt  and detailed reply. I've uploaded the PNG image for reference.

This happens on Android 4.4 and Samsung device so far Galaxy 4, 5 & Note 3. I'm also using the SubscamplingScaleImageView.

Is it necessary to set doubleTabZoom? Also is it better or faster to use a JPG in any way? JPG file size comes out to 3-4 MB instead of 2 with PNG.

![map](https://cloud.githubusercontent.com/assets/1009154/5915004/765337c8-a5cd-11e4-93d6-1811da0b7694.png)

**Comment by davemorrissey** [comment]
This PNG doesn't have an alpha channel so that's one possible cause eliminated. PNG is the best format for an image like this, and I don't think it requires any more memory than a JPG.

You don't need to set doubleTapZoom, it's defaulted to 160dpi which should be okay for most apps. Max scale defaults to the same. That means that when fully zoomed in the image is at 160dpi so even small text on it should be readable, but it won't be completely sharp on a higher density screen.

It does seem to be newer and higher resolution devices affected, though the G4 is not all that new.

I think the best suggestion I have at the moment is to move the image to assets, and reduce the minimumTileDpi to 160.

**Comment by avp2306** [comment]
Thanks. Based on your advice I'm going to go with keeping the PNG format and setMinimumTileDpi(160), also will try avoiding setting the doubleTapZoom for now as that shows up in the call stack (it crashes after users interact with the image).

**Comment by davemorrissey** [comment]
Remember to move the image to assets, the option to display from resources is new and relatively unproven.

If the stack trace is consistent, could you paste it here?

**Comment by avp2306** [comment]
Sure. Also just saw HTC One on the list, FYI.

ava.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:278)
at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:273)
at java.util.concurrent.FutureTask.setException(FutureTask.java:124)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:307)
at java.util.concurrent.FutureTask.run(FutureTask.java:137)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:208)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
at java.lang.Thread.run(Thread.java:864)
Caused by: java.lang.OutOfMemoryError: (Heap Size=43875KB, Allocated=36137KB)
at android.graphics.BitmapRegionDecoder.nativeDecodeRegion(Native Method)
at android.graphics.BitmapRegionDecoder.decodeRegion(BitmapRegionDecoder.java:186)
at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.decodeRegion(SkiaImageRegionDecoder.java:76)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1173)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1150)
at android.os.AsyncTask$2.call(AsyncTask.java:264)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
... 5 more

**Comment by avp2306** [comment]
Based on user reports so far, I'm happy to report that your advice worked :)

Again, much thanks for your help, I commend you on your work & support of this library!

Last detail, I'm looking to have a doubleTap zoom in at about ~70% across devices instead of full 100%, this way the user can zoom in the last 30% if desired. I tried playing with setDoubleTapZoomDpi I dont think I'm using right values. What would be the best way achieve something like that ?

**Comment by davemorrissey** [comment]
That's good news, and quick feedback too!

The default behaviour is to fully zoom in to the max scale on double tap. To change that, you need to set the double tap DPI to a higher value than the minimum DPI (minimum DPI is max scale expressed in a density independent way). You can experiment with these values to get the effect you want.

    setMinimumDpi(160);
    setDoubleTapZoomDpi(200);

BTW if your app is public, let me know if you'd like me to add it to the readme "hall of fame".

**Comment by avp2306** [comment]
Sure thing, much appreciated! here's the link to my app:
https://play.google.com/store/apps/details?id=com.nyctrans.it

Right now the image always loads zoom out initially. Is there maybe a way to set initial zoom, as load the image at 10-15% zoom initially?

Thanks!

**Comment by davemorrissey** [comment]
Really nice app :-)

As you know the dimensions of your image, it's quite easy to set an initial zoom. You just need to calculate the scale you need based on the width and height of your view, and the width and height of the image, then call `setScaleAndCenter` immediately after `setImageAsset`. If you're declaring the asset name in your XML, you may need to move that into code to make this work. It will take a bit of experimentation on screens of different densities to get the effect you want, there isn't really a universal value for 15% zoom.

**Comment by vinothkannahmp** [comment]
Really nice plugin. Thanks, saved lot of time for me.

I faced this issue frequently on samsung tab when I use SubsampleScaleImageView in ViewPager.

Cause: My device doesnt allocate memory more than 45MB (approx) to my device.

Fix: Set android:largeHeap="true" in application tag of AndroidManifest.xml
and in onPause() of fragment or activity set <SubsampleScaleImageView>.recycle();
