### ISSUE TITLE
Image padding

### ISSUE THREAD

**Issue by laurencedawson** [davemorrissey/subsampling-scale-image-view#39]
Hey, just discovered the lib and great job.

I'm currently using PhotoView which allows padding on images. As far as I can tell padding is ignored when determining the initial image size when using subsampling-scale-image-view.

If it helps this was the previous issue raised for PhotoView:

https://github.com/chrisbanes/PhotoView/issues/29

Cheers

**Comment by davemorrissey** [comment]
I might be able to add this soon, but would a margin not do the same job?

**Comment by laurencedawson** [comment]
Setting a margin would stop the image from expanding into the region. I've attached an image to show this:

![Uploading padding.png . . .]()

**Comment by laurencedawson** [comment]
I'm currently looking to integrate this into "Swipe for reddit" and then "reddit sync".

**Comment by davemorrissey** [comment]
Okay, that makes sense but I'm not sure this is how I'd interpret padding. That said, there's no more logical behaviour for padding on this view (since it doesn't support child views or display text) so I might be able to implement this. I'm snowed under at the moment so I have a couple of other alternatives, which I haven't tried but I think will achieve this.

I assume the view is the full size of the screen whether the chrome is displayed or not, and the chrome is an overlay.

The first option is to fit the view inside the chrome when it's visible, and expand it to full screen on tap. The view's `onSizeChanged` method preserves the scale and center, so in theory, as long as the header and footer are the same height, the image should not move or scale when you hide the chrome.

The second option is more complicated, and also assumes the header and footer are the same height.
* Extend the class
* Override `onImageReady`
* When `onImageReady` is called, calculate a scale that will reduce the image to the correct size using the image dimensions, view dimensions, and header and footer height.
* Set the minimum scale and current scale to this value.
```
    float scale = Math.min(getWidth() / (float) sWidth(), (getHeight() - (2 * [headerHeight])) / (float) sHeight());
    setMinimumScaleType(SCALE_TYPE_CUSTOM);
    setMinimumScale(scale);
    setScale(scale);
    invalidate();
```

**Comment by davemorrissey** [comment]
If that doesn't work, take a look at the other public and protected methods, because I'm reasonably confident there's a solution that doesn't require changes to the class itself.

**Comment by laurencedawson** [comment]
The margin method does work but this stops content being shown behind the transparent bottom bars when a user zooms in.

I couldn't quite get your second scale based method to work. Seemed to not display.

**Comment by davemorrissey** [comment]
I deleted the first method from my comment because I realised it wouldn't work, although not for the reason you've described.

Could you send your layout file and the subclass for the second method?

**Comment by laurencedawson** [comment]
This is my simple implementation. I'm posting a runnable as "onImageReady" seemed to call back on a non-ui thread...

https://gist.github.com/laurencedawson/21028a35f55ba14205d3

Thanks for the help!

**Comment by davemorrissey** [comment]
Thanks for that, there's just one thing I need to know, and that's how you hide the chrome and what happens to the image view when you do. When the chrome is visible is the view sized to fit within it then resized to full screen on tap, or is the chrome an overlay so the view is the full size of the screen whether the chrome is visible or not?

**Comment by laurencedawson** [comment]
The SubsamplingScaleImageView is the first child in a RelativeLayout with a Toolbar and LinearLayout overlaid. 

Hiding the chrome does not change the size of the SubsamplingScaleImageView.

**Comment by davemorrissey** [comment]
I've spotted a bug in the `setMinimumScaleType` method - it results in the view redrawing using the initial value of `minScale` which is zero, so key state variables get set to `NaN`. I'll fix this, but there's an easy workaround for you - just move the `setMinScale` line above `setMinimumScaleType`.

`onImageReady` is called off the UI thread to make sure that if subclasses do any heavy lifting in that method, the rendering is not blocked.

A bit of additional hacking is required to stop the image from appearing briefly at full size before the padding takes effect. This appears to work well enough: https://gist.github.com/davemorrissey/9133860908fb4977644c

**Comment by laurencedawson** [comment]
That seems to have done the trick! Thanks.

**Comment by davemorrissey** [comment]
No worries. I'll think about how to support padding, the thing I need to work out is how it should behave if top padding is different to bottom padding so the image starts off-centre. I may not support that.

Would you like your apps listed in the readme?

**Comment by laurencedawson** [comment]
I think PhotoView only supports identical padding too.

**Comment by davemorrissey** [comment]
I have added padding support (including asymmetric padding) to the view. I'll release a new version in a few days.

**Comment by laurencedawson** [comment]
Awesome thanks!

**Comment by laurencedawson** [comment]
Any chance I could get a look at the code pre committing? Thanks

**Comment by davemorrissey** [comment]
I've already pushed the code changes, but not built a new release yet. See https://github.com/davemorrissey/subsampling-scale-image-view/commit/e88575898e49725160685298db718b1bae6b36db
