### ISSUE TITLE
RegionDecoderOnly flag

### ISSUE THREAD

**Issue by rcketscientist** [davemorrissey/subsampling-scale-image-view#429]
First of all, thanks for this library.  I have an app that was previously using a bastard child of the old AOSP Gallery and the Big Image sample.  It was fast, but errors were unintelligible and the code didn't have a modern flow to it.  So I appreciate how hard this is.

I have an app that decodes raw images (now with a custom `ImageRegionDecoder`).  As such there's very little use for a `ImageDecoder` since there's no efficiency gained.  **Would there be any impact to adding a flag to always use the `ImageRegionDecoder`.**  Sometimes there's very small thumbnails.

**If I wanted to do the decode in two passes (thumbnail -> full decode), is that supported?**  Some thumbnails are quite large, so I wouldn't want to use the preview.  I imagine I could  potentially replace the `BitmapRegionDecoder` within the custom `ImageRegionDecoder` if I could avoid threading issues.

**Comment by rcketscientist** [comment]
I've been digging a little deeper into how to solve my various nuances.  Is there any particular reason that `ImageSource` is `final`?  Taking that a bit further, I'm thinking it would be useful as an interface where the image source could supply the decoder.  You might have: `BitmapSource`, `UriSource`, `ResourceSource`, `MySource`.  The first three might be packaged, the last would be custom and link it's custom decoder.

An additional benefit would be extensible source types.  I have a data model that contains image-type.  Primarily, I'm interested in the uri (which works), but it helps to have the full data model which can help to choose the decoder (TIFF, RAW, JPG, etc.).  If the `ImageSource` supplied it's own decoder it might minimize some of the one-size-fits-all (bitmap, uri, etc.) and eliminate the external config (`setRegionDecoderClass`).  Let me know if I'm missing something in my cursory analysis.

**Comment by davemorrissey** [comment]
Given your specialised requirements I think the best option would be to fork the library and make a few tweaks. There may be workarounds - if you know the dimensions in advance you can specify a region covering the whole image and that disables the fallback to `ImageDecoder`, or you can give a factory class that returns the same object instance for both decoder classes, but a modified fork would be cleaner.

`ImageSource` and most of the library is final because I wanted to be very clear about what overrides are supported, and prevent subclasses putting the view into unexpected states. I was worried I'd get a lot of bug reports from developers who unwittingly broke the "state machine". The protected methods are probably a mistake, they should be package private. Again, forking is the solution here.

Source interfaces might have worked as an alternative design, but wouldn't necessarily be simpler because the view needs to know whether region decoding and subsampling is supported by the source and whether it should get the bounds and load tiles asynchronously. The `ImageSource` class is concerned with the source of the image data, not the format of that data, so I think trying to merge them would make the view more complicated to use.

**Comment by rcketscientist** [comment]
Thanks for the fast reply.  I can certainly understand wanting to avoid downstream headaches.  

I did fork and start playing with it.  The very tight coupling of `ImageSource` and ssiv certainly make it a lot messier than my posted overview, but I think there's more than one way to crack this egg.  I'll probably start by forcing a single decoder so it never gets decoded twice with an extended `ImageSource` and `ImageRegionDecoder` taking an `ImageSource` rather than `Uri` for access to meta.  Should stay close enough to upstream to be maintainable.

**Comment by davemorrissey** [comment]
Did you manage to get it working the way you wanted?

**Comment by davemorrissey** [comment]
If images are not prefetched it's usually because the view has no dimensions so cannot tell what tiles it should load. Make sure the offscreen page limit is set appropriately.

I'll close this for now, but if you have changes on a fork that might be useful for others, please comment here again!
