### ISSUE TITLE
Is possible using this component with layout wrap_content?

### ISSUE THREAD

**Issue by PetrDana** [davemorrissey/subsampling-scale-image-view#43]
Hi,

please, is possible using this component with layout wrap_content in width and height? When I set this value, view is over all display and after load image it is resized, but panning and zooming are broken - image is not visible whole, panning not work when zoom is out and when I zoom, panning is possible only with partial content.

And if this view is possible using with wrap_content, why is over all display before image file loading? (This breaks dialog in which this view is placed.)

Thank you for help.

**Comment by davemorrissey** [comment]
This view has limited support for wrap_content, because wrapping the content has no obvious meaning when the content is scalable. If you use wrap_content for both width and height, it will scale the view to the full size of the image at 100% scale (1:1 pixels) once the view has loaded. If you use one fixed dimension and one wrap_content, it will resize the view to have the same aspect ratio as the image. In either case, the view fills its parent until the image size is known - it is not possible to use zero width or height because Android will not attempt to draw the view.

You have a few options:
1) Fix the width with match_parent and let the height scale with wrap_content.
2) Put the view inside another view that has the dimensions you want, and set it to fill_parent for both dimensions.
3) Create a subclass and override onMeasure to provide the behaviour you want.
