### ISSUE TITLE
Samsung Note3 5.0 cannot display image

### ISSUE THREAD

**Issue by hongtou820** [davemorrissey/subsampling-scale-image-view#456]
view.setImage(ImageSource.resource(R.drawable.ic_map)); 

cannot display out on Samsung Note 3 android 5.0
other phone no problem

**Comment by hendrawd** [comment]
Also can't display on Infinix Zero 5 model X603 with android version 7.0

**Comment by hendrawd** [comment]
I need to set error and placeholder image for `SubSamplingScaleImageView` when loading an image from the server. There is no problem when load success, because set image via bitmap. For placeholder and error, I have to use image resource, so for a workaround, I have to use 1 more `ImageView` to set image resource.

**Comment by davemorrissey** [comment]
With the issue template deleted, and the image, layout etc. not provided there is not enough information to reproduce this issue. Make sure the image is in drawable-nodpi or put it in assets instead.
