### ISSUE TITLE
Draw polygon shape with clickable event on image

### ISSUE THREAD

**Issue by persource** [davemorrissey/subsampling-scale-image-view#462]
Draw polygon clickable shape on image with scrollable. [Here is the good library that handle this](https://github.com/catchthecows/AndroidImageMap/blob/master/src/com/ctc/android/widget/ImageMap.java) but unfortunately mashup the polygon when image is too large (4000x4000).

Subsampling-scale-Image-view is good library that handle large image, so my question is that anyway to draw polygon shape over this and it should not disturb after zooming?

**Comment by Benyuss** [comment]
I just did a very similar stuff to yours.

Overwrite this imageView class as seen in the examples.
Put this to your onDraw

`polygons?.clear()
polygonDrawer?.let {
            it.polygons.forEach { polygon->
                sourceDrawerToViewCoord(it, polygon)
                drawPolygon(canvas, polygon)
            } 
      }`

Kotlin extension to handle zooming of polygons.

`fun SubsamplingScaleImageView.sourceDrawerToViewCoord(polygonDrawer: PolygonDrawer, polygon: polygon) {
    polygonDrawer.drawablePoints.clear()
    polygon.coordinates?.forEach {
        val viewPolyPoint= PointF()
        sourceToViewCoord(((it.x).toFloat(), ((it.y).toFloat(), viewPolyPoint)
        polygonDrawer.drawablePoints.add(viewPolyPoint)
    }
}`

PolygonDrawer class

`class PolygonDrawer (var context: Context, var polygons: MutableList<Polygon>) {

    var drawablePoints: MutableList<PointF> = arrayListOf()
    var polygons: HashMap<Long, Polygon> = hashMapOf()

    fun drawPolygon(canvas: Canvas, color: Int) {
        // line at minimum...
        if (drawablePoints.size < 2) {
            return
        }

        // paint
        val polyPaint = Paint(Paint.ANTI_ALIAS_FLAG)
        polyPaint.color = ContextCompat.getColor(context, color)
        polyPaint.style = Paint.Style.FILL

        // path
        val polyPath = Path()
        drawPathFromPoints(polyPath, drawablePoints)

        val poly = Polygon.Builder()
        drawablePoints.forEach {
            poly.addVertex(Coordinate(it.x.toDouble(), it.y.toDouble()))
        }
        polygons[locationId] = poly.build()

        // draw
        canvas.drawPath(polyPath, polyPaint)
    }

    private fun drawPathFromPoints(polyPath: Path, points: List<PointF>) {
        //go to first point
        polyPath.moveTo(points[0].x, points[0].y)

        points.forEach { point ->
            polyPath.lineTo(point.x, point.y)
        }

        //go to first point again to close the polygon.
        polyPath.lineTo(points[0].x, points[0].y)
    }
}`

Polygons class is from here [https://github.com/sromku/polygon-contains-point/tree/master/src/main/java/com/snatik/polygon](url) because i needed a mechanism where i check if a polygon contains a point (where the user taps) to recolor my polys.

This will handle polygon drawing, scaling, zooming.
You can have as many polygons as you want.

**Comment by persource** [comment]
@Benyuss Thanks for the code. It's unclear for me how it used with SubsamplingScaleImageView and some of the terms like coordinates of polygon. Cleaner code would help me to understood.

**Comment by srbhagwatsrb** [comment]
@Benyuss @persource  Could you please post the complete code? I am unable to get this to work.

**Comment by davemorrissey** [comment]
Closing this as it's a request for helping building an app and not an issue or feature request. Good luck!
