### ISSUE TITLE
setOrientation(Int) doesn't trigger onViewPortChanged()

### ISSUE THREAD

**Issue by hereisderek** [davemorrissey/subsampling-scale-image-view#478]
quick fix by adding 
`         sendStateChanged(scale, vTranslate, ORIGIN_PROGRAMMATIC); `
into setOrientation() results in the following

``` java
    public final void setOrientation(int orientation) {
        if (!VALID_ORIENTATIONS.contains(orientation)) {
            throw new IllegalArgumentException("Invalid orientation: " + orientation);
        }
        this.orientation = orientation;
        sendStateChanged(scale, vTranslate, ORIGIN_PROGRAMMATIC);
        reset(false);
        invalidate();
        requestLayout();
    }
```

open for discussion for a better solution (if there's any caveat)

**Comment by davemorrissey** [comment]
setOrientation does not call sendStateChanged because the intention is to call back to the app's code when state changes are initiated within the view. An orientation change is triggered from outside the view, by the app's own code, so it shouldn't need a callback for that.
There is no change to the viewport when rotating an image so it shouldn't trigger onViewPortChanged.
