### ISSUE TITLE
Moiré patterns occur at certain zoom levels

### ISSUE THREAD

**Issue by ansman** [davemorrissey/subsampling-scale-image-view#49]
It's a bit hard to tell by the image but the sky in the image has a dot like pattern that is quite obvious on a real device:
![Example](http://f.cl.ly/items/0S1M0P0I44023Y0h3L0N/device-2015-03-09-110247.png)

This can be solved by using `Config.ARGB_8888` instead of `Config.RGB_565`.

I totally understand why 565 is default but it would be nice if you could choose which one that is used without having to create a whole new custom decoder.

**Comment by ansman** [comment]
It can also be fixed by disabling dithering.

**Comment by davemorrissey** [comment]
This suggests the original image may have come from a scan, I've never seen a moiré pattern on an ordinary photo. I can understand why RGB_565 might cause this but I've never seen it.

I'm not keen to provide an option to use ARGB_8888 because this will cause a lot of crashes for many people. Also the custom decoder work made it much more difficult to generically provide options like this, but perhaps there's a way to do it. I'll have a look.

**Comment by ansman** [comment]
Every single photo I've loaded shows this behaviour (I'm using a Nexus 5).

**Comment by davemorrissey** [comment]
Please could you attach that image so I can test with it? My phone has a pentile screen and I think that makes it a bit harder to see the pattern.

**Comment by davemorrissey** [comment]
I've disabled dithering. It doesn't seem to affect quality much and fixes the problem. Would you be happy with that?

I can add support for custom decoding options if required, but it's a breaking change for anyone who's implemented a custom decoder. There are other breaking changes in v3.0.0 released yesterday so now would be as good a time as any to do it, I'm just wary of allowing ARGB_8888 because I know it will cause a lot of crashes.

**Comment by davemorrissey** [comment]
Released in v3.1.0.

**Comment by ansman** [comment]
Works like a charm, thanks!
