### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by ZacSweers** [davemorrissey/subsampling-scale-image-view#493]
Last commit was over 1+ year ago and there are a lot of open issues and PRs. Asking for visibility from the community

**Comment by rafid059** [comment]
the most active fork https://github.com/tibbi/subsampling-scale-image-view

**Comment by ZacSweers** [comment]
Is there any information about the goals of that fork? I see a lot of code removal in the commit history but wasn't able to see anything about the goals or overview of the project. It appears to use all the same package names and installation info as this project as well.

**Comment by rafid059** [comment]
The fork's readme needs a serious update. Not sure about the goals of the fork but the author seems to maintain it pretty well, including bug fixes and dependency updates. We are still on this original lib but looking to move over to the fork.

**Comment by davemorrissey** [comment]
I haven't actively developed anything on Android for a few years, and with the constant changes to the ecosystem it's not possible to keep up. I've been unsure about whether migrating to AndroidX, Kotlin etc. is necessary for a library, and whether it would break apps that haven't been migrated.

As far as I'm aware, most of the open issues are requests for help, rare edge cases, specific device or image issues, feature requests, or a result of not reading the guides. Very nearly everyone deletes the issue template and leaves no information required to reproduce issues, so it's been a long time since there was an issue where I could release a fix that benefits the majority.

I think that the library still does what it needs to for the vast majority of developers and has all the features I plan to implement - or at least I haven't seen an issue that clearly says it doesn't - so I've left it unchanged for a while.

Tibbi's fork was created for the Simple Gallery app. It has customisations for that, but still seems good for general use. Not sure if there's any guarantee of that, or whether it's available in a maven repository.

**Comment by ZacSweers** [comment]
Would you be open to a PR to migrate to androidx and a final release with that? It does work, but androidx is a tax being paid by everyone consuming this now as it requires them to have jetifier enabled until every library used in their stack is updated. In our case, this is one of the last ones not to have updated yet.

**Comment by davemorrissey** [comment]
I haven't done anything with AndroidX and it might take a while to get my aging Macbook up to spec but this should be possible. Could you take a look at #447 and see if it's right? Alternatively, you could make your own PR.

**Comment by ZacSweers** [comment]
Just took a review pass on it and that looks good to me 👍. It's a little old (compile SDK could be set to 29 now + there are newer stable versions of Gradle and AGP), but from an androidx front that looks good.

**Comment by davemorrissey** [comment]
I have released this with library and tool versions updated (commit not pushed yet) and the artifact name changed to `subsampling-scale-image-view-androidx`. Package and version unchanged. I have not tried it myself, please could you give it a try and see if it works?

**Comment by ZacSweers** [comment]
Just tried it in our app and looks like it's working fine for us 👍

**Comment by ZacSweers** [comment]
I would recommend keeping the same artifact for compatibility. Having different coordinates with the same package name can cause some significant classpath conflicts if a consumer has a transitive library that hasn't updated. Several libraries have updated to androidx without considering it a major version since the jetifier tool makes it non-breaking

**Comment by ZacSweers** [comment]
Or - release it as 4.0 if you're worried about semver for it anyway. Since it might be the last release of this, it doesn't seem like a big issue one way or the other. Keeping a separate artifact with the same package name however can cause headaches downstream. RxJava pivoted away from this in RxJava 3.

**Comment by madmas** [comment]
@davemorrissey good to see some activity here, thank you!
As I just wanted to check out the subsampling-scale-image-view-androidx version - where have you published it?

**Comment by davemorrissey** [comment]
It's in maven central so if you add `com.davemorrissey.labs:subsampling-scale-image-view-androidx:3.10.0` to your project it should work.
