### ISSUE TITLE
Why do I get "Bitmap too large to be uploaded into a texture" error

### ISSUE THREAD

**Issue by osrl** [davemorrissey/subsampling-scale-image-view#51]
I use picasso to load the bitmap from network. Small images are loaded, with larger images I get "Bitmap too large to be uploaded into a texture" error (a lot of them). Tiling is not disabled.

```
Bitmap too large to be uploaded into a texture (5000x2813, max=4096x4096)

**Comment by davemorrissey** [comment]
The view can't tile the image if you provide it as a `Bitmap` object. You should save it to temporary storage and provide the file URL instead.

**Comment by davemorrissey** [comment]
I will see if it's possible to tile a `Bitmap` object when it's larger than the max texture size. However, you should be aware that an image this large will cause `OutOfMemoryError`s on many old or budget devices, and it is always best to write the raw image data to disk then use the file path instead of creating a `Bitmap` from it.

**Comment by osrl** [comment]
If `OutOfMemoryError ` is still on the table when you tile the `Bitmap`, think it is not needed. I did what you suggest. Thank you.

**Comment by davemorrissey** [comment]
You're welcome, thanks.
