### ISSUE TITLE
PNG Compatibility

### ISSUE THREAD

**Issue by AlexVPerl** [davemorrissey/subsampling-scale-image-view#520]
This is more of a question than an issue, so apologize if this isn't the right place for it. Question is about non transparent PNG compatibility across Android devices. I remember a while back, there was an issue with how certain devices load PNG, so for best compatibility JPEGs were recommended. 

Is this still the case with newest library releases? If so, what would you recommend for getting PNGs working properly as in are there any workarounds or any specific way/format PNG should be saved as.

Any additional info based on your experience with this would be appreciated. Thanks!

**Comment by davemorrissey** [comment]
The issue with CMYK and grayscale PNGs was due to a bug in Skia, the image rendering library in Android. It's been years since anyone reported that issue so I can only assume it's been fixed.

Everything I knew at the time I documented here: https://github.com/davemorrissey/subsampling-scale-image-view/wiki/04.-Custom-decoders

**Comment by AlexVPerl** [comment]
Thanks for clarifying.
