### ISSUE TITLE
about fresco

### ISSUE THREAD

**Issue by zeng1990java** [davemorrissey/subsampling-scale-image-view#62]
There are plans to support Facebook fresco？

**Comment by davemorrissey** [comment]
Not at present. I'm not sure how or if the two libraries would work together.

**Comment by zeng1990java** [comment]
ths.I will pay attention to the project.

**Comment by davemorrissey** [comment]
I'm going to close this for now because I don't think there's much functionality Fresco provides that could be integrated into this view. I'm watching the Fresco project to see if that changes - there's an open issue in that project about it being unable to display very large images, and commenters there have recommended SSIV instead.

**Comment by Piasy** [comment]
I've just created a big image viewer supporting pan and zoom, with very little memory usage and full featured image loading choices. Powered by Subsampling Scale Image View, Fresco, Glide, and Picasso https://github.com/Piasy/BigImageViewer , hope it helps :)

**Comment by jinshiyi11** [comment]
we are using fresco.fresco can resizing jpg but if we want to resizing png,we need to set  setDownsampleEnabled to true.It is an  experimental feature and will affect all exist logic. Will SSIV support fresco？
