### ISSUE TITLE
Tiling not working when minimumScaleType is set

### ISSUE THREAD

**Issue by fvink** [davemorrissey/subsampling-scale-image-view#63]
I'm trying to limit how far the image can be zoomed out by calling setMinimumScaleType(SubsamplingScaleImageView.SCALE_TYPE_CENTER_CROP) and setMinScale but setting the scale type disables tiling. I'm not sure if that's what's supposed to happen. If so, is there any other way to accomplish what I'm trying to do?

**Comment by davemorrissey** [comment]
I think there's a bug in the minScale setting, it doesn't set the minimum scale type to SCALE_TYPE_CUSTOM as it should, so if you have set the scale type to center crop, the min scale setting will be ignored. However, this does not disable tiling. What it may do is cause the loading of full resolution tiles immediately because the image is rendered zoomed in immediately.

Can you describe in more detail exactly what you're seeing, and try the debug setting to understand what tiles are being loaded and rendered?

**Comment by fvink** [comment]
Actually when I set the center crop the min scale works, it limits how far I can zoom out, but there are no tiles. There is only one Rect for the whole image in full resolution and as I zoom in it stays like that. No new Rects appearing.

**Comment by davemorrissey** [comment]
That must mean the image is not large enough to need tiling on that screen. If you try with a larger image or a low resolution screen it will tile the image if necessary.

**Comment by fvink** [comment]
The screen is 720p and the image has a resolution of 3000x2000. When the tiling doesn't work the scrolling, panning and all that stuff lags because of the size of the image.

**Comment by davemorrissey** [comment]
It sounds like the view is doing what it's supposed to. It will not tile the image if all the tiles would be needed when you are viewing the center of the image, and I believe that's true in this case.

**Comment by fvink** [comment]
Wouldn't only the tiles that are in the center be needed, depending on the current scale? So if only the center of the image is visible, and side parts are not, shouldn't only the center tiles load?

If that's what's supposed to happen, is there another way to limit maximum zoom out so the image always fills the vertical space but is enabled to scroll left and right?

**Comment by davemorrissey** [comment]
Assuming your screen is 720x1280, and the image 2000px high it needs to be loaded at full resolution to equal or exceed the resolution of the screen. The view will never tile the base layer unless the image exceeds the canvas maximum bitmap size because this leads to the image being visibly loaded in sections and actually makes the loading slower. The view must have the whole base layer loaded into memory or you would get black areas while panning. Rendering only the visible area would make little difference to rendering performance in this case.
