### ISSUE TITLE
Recycle not releasing memory

### ISSUE THREAD

**Issue by rhinobomb** [davemorrissey/subsampling-scale-image-view#66]
I've been using this view to display full screen images and am having trouble keeping memory usage under control.  I've been calling recycle on my view to release memory when not in use and reset for re-use but it doesn't seem to change how much memory my app is using.  I've even gone as far as to put together a simple app for a test that calls a function to recycle the view when clicked.  The function fires but the memory usage stays the same.  Do I have to do more than just call recycle on the view?

**Comment by davemorrissey** [comment]
Recycle is not guaranteed to release memory immediately but it will make the objects available for garbage collection when the memory is required. The contract of the SubsamplingScaleImageView recycle method is similar to that of the [Bitmap class recycle method](http://developer.android.com/reference/android/graphics/Bitmap.html#recycle%28%29) (this is the method it uses to recycle the tiles).

If you want to prompt garbage collection call `System.gc()`, but note this isn't guaranteed to do anything and calling it is usually considered bad practice.

**Comment by rhinobomb** [comment]
Thanks for the response, that makes sense.  I guess maybe I'm having another issue then.  I'm using a view pager to create something very similar to a gallery with full screen images.  It's working well to the point I'm trying to load a different layout in a new fragment.  For testing purposes I've made the layout almost identical to the rest of the fragments and I'm still having issues.  I'm using a consistent image size with similar content but I'll get one image to load fine and the next one will cause OOM.  Maybe I don't know enough about view pagers and fragments and using multiple layouts is bad practice, I'm not really sure.  Is there some way I could block the call to setImage in a try/catch I can try to recover the app?  I'm not sure it would make a difference to what advice you give but the OOM is coming from TileLoadTask.doInBackground

Thanks again.

**Comment by davemorrissey** [comment]
I'm not sure what to suggest, my sample app has a view pager which works without any problems, even when zoomed in, but those images are quite small. I know others have built apps with view pagers and haven't reported this problem.

The first thing to check is that you are not using PNGs with an alpha layer, and the next thing you can try is reducing the minimum tile DPI setting so you get a slightly more blurry image on high resolution devices but less image data is loaded. If all else fails, you will have to recycle the outgoing view then the pager starts instead of when you start loading the next image, but I don't think that should be necessary and it is likely to blank the screen while moving between pages.

**Comment by davemorrissey** [comment]
As I don't have any further advice to give I'll close this for now. If you find a way to reduce memory usage in a view pager please let me know!
