### ISSUE TITLE
Is it possible to preload the tiles such that it looks more smooth?

### ISSUE THREAD

**Issue by alex621** [davemorrissey/subsampling-scale-image-view#74]
We have a list view with some long posts in it. When we scroll down the list view, the cell will first look blank then the image loads. This does not look good. We want to show the image immediately when the cell is drawn. Is it possible? Thanks.

**Comment by davemorrissey** [comment]
I'm not sure I understand what you're doing but the view cannot load an image until it's on the screen because it may have no dimensions, and dimensions are required to load an initial image of the correct resolution. The view initialises in onDraw, because when this is called it's almost certain the dimensions are set.

**Comment by alex621** [comment]
We already have the dimension of that image (returned from our server). For our case, the dimension of that view can also be calculated. So basically we should be able to calculate before it is drawn.

**Comment by davemorrissey** [comment]
Preloading several images like this, if they are large, is very likely to cause OutOfMemoryErrors. Unfortunately this is not something I can support because it requires significant changes and would cause users a lot more problems - some already report problems when they have two or more views loaded at the same time.
