### ISSUE TITLE
Lag when used in a viewpager

### ISSUE THREAD

**Issue by eshanj19** [davemorrissey/subsampling-scale-image-view#75]
Hi Dave,

  I am trying out your library and it is fanatastic.But I am having problems with lag in viewpager.I am setting imageview like this in my gallery fragment  and I notice lag while swiping from one fragment to another.
                imageView.setImage(ImageSource.uri(imageKey));
While other apps using this library like Tag gallery dont face this issue. When zoomed in, the image appears blurry at first but then becomes sharp and clear. This behavior is not observed in my fragment.
The image is never blurry when zoomed in. 
Obviously I am doing something incorrect. can you help me out?

**Comment by davemorrissey** [comment]
If the image is not large enough to require subsampling, it won't be blurry when zoomed in. This is more common on high resolution devices.

**Comment by dustin-graham** [comment]
@davemorrissey I'm also troubled with loading delays when using this inside of a ViewPager. I'm expecting the Fragments to the left and right to load and be ready when I swipe. However, it doesn't matter how long I wait on one of the pages, the adjacent pages only get loaded after I swipe. Is there a trick to make the imageview load it's image ahead of time?

**Comment by davemorrissey** [comment]
Hi Dustin, #74 and #59 are more closely related to your question. The view can't load an image until it has dimensions because it doesn't know what subsampling level to apply to the full size image, and whether it needs to load the base layer in tiles due to bitmap size restrictions. Views don't tend to get laid out until they are visible, and because this coincides with the first call to onDraw, that's where the view completes its setup and starts loading tiles.

It may be possible to add the option to set the expected dimensions of the view before it's visible, allowing it to start loading, or alternatively for the view to default to assuming it will fill the screen. Both of these would require some restructuring.

**Comment by KeesR** [comment]
Hi all,
Had same issue as issue reporter. I followed up on Dave's suggestion ("It may be possible ...") to trigger the base image loading when setting the imageSource (in my case a fileName).

Looking at the code, I saw some state is not set yet at that moment, blocking base layer loading.

The following (Kotlin) code in ViewPager instantiateItem() ensures enough state is set:

```
//  Two conditions need to be fulfilled to ensure the view will load its base layer
//  immediately, before onDraw():
//  1   The image region must be set --> set it to image size
val imageFilename = imageList[position].data    //imageList is my data structure
val imageRect = getImageRect(imageFilename)
val imSrc = ImageSource.uri(imageFilename)
imSrc.region(imageRect)

//  2   Automatic tile sizing blocks base layer loading --> set a max tile size
ssImageView.setMaxTileSize(4096)     // see note

//  Now we can add the image 
ssImageView.setImage(imSrc)
```

With this code in place, 'lagging' will only occur when you swipe your images faster than the base layer loading.
Notes: the hardcoded constant here could be replaced with something more sensible. GetImageRect() utility function could be based some code in the decoder code in library.
Hope this is useful.
