### ISSUE TITLE
Bitmap too large: Bitmap too large to be uploaded into a texture (7040x3680, max=4096x4096)

### ISSUE THREAD

**Issue by beniroquai** [davemorrissey/subsampling-scale-image-view#85]
I've a large JPG ca. 7000x5000 px. I load it via:

```
private void initialiseImage(String chosenDir) {
        try{
            SubsamplingScaleImageView imageView = (SubsamplingScaleImageView)findViewById(R.id.imageView);
            String file = String.valueOf(chosenDir);
            Bitmap bmp = BitmapFactory.decodeFile(file);
            imageView.setImage(ImageSource.bitmap(bmp));
        }
        catch (Exception e){
            Log.e("File", "File not found!");
        }
    }
```

I simply downloaded the Sample-App and copied the ```BasicFeatureActivity``` into my project. I added the dependencies and libraries to my project in Android studio. When use the plain Sample app and load the image from assets it works. 

Any idea why I get the
```Bitmap too large to be uploaded into a texture (7040x3680, max=4096x4096)``` Error?

Thank you! :)

**Comment by davemorrissey** [comment]
The view will not subsample or tile a preloaded bitmap. You need to provide the file path and allow the view to do the decoding.

**Comment by beniroquai** [comment]
Thank you very much. This solved my problem!
Am 03.07.2015 08:17 schrieb "davemorrissey" <notifications@github.com>:

**Comment by ArLabDev** [comment]
Is it still unsupported big textures from Bitmap?

**Comment by davemorrissey** [comment]
Yes, the same advice still applies.

**Comment by ArLabDev** [comment]
Just tried, on 3.10 still give OpenGLRenderer error

**Comment by davemorrissey** [comment]
If you're reporting a bug I need the code, error, image and device.

**Comment by ArLabDev** [comment]
@davemorrissey, not reporting a bug.
If this is the expected behavior, it is not a bug. In fact, when I used your viewer, I didn't realize that it won't work on big images using ImageSource.bitmap().
Just asked if now it works.

It has reported to me a bug in my app on a quite old device that has 16Mpixel camera and 4096x4096 textures. So it crashed. now devices has bigger textures and camera image is no more a problem.
To fix the problem for a device I need to save the image on disk and then ask to the viewer to reload it. Time and memory spent on all devices just for a problem on few ones.
I'm wondering if there is a fast way to get maximum texture size (it seems that I have to allocate OpenGL surface to do that)

Anyway, just explaining my problem.
Thanks to you for your great viewer.

**Comment by davemorrissey** [comment]
I'm not aware of any easy shortcut but you could create an empty view subclass early in your app so you can override onDraw and make a note of the max bitmap size for later.
